# Generated by Django 2.2.7 on 2019-11-19 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentPathways',
            new_name='PaymentPathway',
        ),
        migrations.RenameModel(
            old_name='SubType',
            new_name='SubTime',
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name_plural': 'Licenses'},
        ),
        migrations.AlterModelOptions(
            name='licensestatus',
            options={'verbose_name_plural': 'License Status'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='paymentpathway',
            options={'verbose_name_plural': 'Payment Pathways'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name_plural': 'Registrations'},
        ),
        migrations.AlterModelOptions(
            name='submodel',
            options={'verbose_name_plural': 'Subscription Models'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='subtime',
            options={'verbose_name_plural': 'Subscription Time'},
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Frenchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ismain', models.BooleanField(default=True)),
                ('phone', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(default='Unknown', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.City')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Organization')),
            ],
            options={
                'verbose_name_plural': 'Frenchises',
            },
        ),
    ]
