# Generated by Django 2.2.7 on 2019-11-21 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191121_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='active',
        ),
        migrations.AlterField(
            model_name='licensestatus',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='pathway',
            field=models.ForeignKey(default='Free', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.PaymentPathway'),
        ),
        migrations.AlterField(
            model_name='submodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subtime',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
