# Generated by Django 2.2.7 on 2019-11-21 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191121_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='suscription',
            new_name='subscription',
        ),
    ]
